### PR TITLE
Support PHP 8

### PR DESCRIPTION
**Pull request by francislavoie**
Let's see if this works 🤞 

See #282

### CODE REVIEW

**Comment by francislavoie** [comment]
Welp, two problems

- Lots of phpstan errors
- `endroid/quality` requires `^7.4`, so `7.3` tests fail. (Please continue to support 7.3!!)

**Comment by francislavoie** [comment]
Okay well we need https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/103 to be merged.

**Comment by francislavoie** [comment]
Asking how to handle the phpstan isses 😅 https://github.com/phpstan/phpstan/issues/4170

**Comment by francislavoie** [comment]
Looks like the tooling needs to be updated to a version that uses at least `nette/utils` `v3.0.4`: https://github.com/nette/utils/releases/tag/v3.0.4

```
PHP Fatal error:  Uncaught TypeError: _HumbugBoxbfaeed0746fa\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned in phar:///home/runner/work/qr-code/qr-code/vendor/bin/phpstan/vendor/nette/utils/src/Utils/Reflection.php:157
```

**Comment by endroid** [comment]
Hi @francislavoie good job. I manage my CI workflow via the endroid/quality package so there is no need to update anything here. You have some nice additions to the workflow so I updated it there and made sure the 3.x branch here uses that workflow. This should also fix the phpstan issue (which was fixed in a later version of my endroid/quality package).

So if you merge the new changes you should be able to continue.

**Comment by francislavoie** [comment]
Great!

We're still waiting for khanamiryan/php-qrcode-detector-decoder#103 of course, but yeah I'll rebase soon in the meantime (stepped away from my PC)

**Comment by francislavoie** [comment]
I think we want to actually omit the param/return types in `PngWriter.php`, because PHPStan can infer most of them (specifically the `resource` ones, because that breaks 7 + 8 compat with PHPStan)

**Comment by endroid** [comment]
@francislavoie maybe the is_object workaround described here works: https://php.watch/versions/8.0/gdimage

**Comment by francislavoie** [comment]
That won't work, that's what I had originally if you see https://github.com/phpstan/phpstan/issues/4170

The issue is that GdImage doesn't exist in one version, and a resource is not an object in the other. There's no type overlap at all.

**Comment by francislavoie** [comment]
I'm thinking that code quality checks should only be run on one PHP version (on 8 I guess) because we'll have type contention no matter what.

**Comment by francislavoie** [comment]
🤦‍♂️ 

Well it seems psalm didn't get the memo about PHP 8 language changes 😂

**Comment by endroid** [comment]
@francislavoie I will keep the CI workflow as it is in 3.x and try if I can find a setup that also works in PHP 8. Currently the build only fails on the actual phpunit tests and static analysis seems to pass (with some less strict type checking, but I will have to take that for granted). Let's wait for the detector compatibility before we go any further.

**Comment by francislavoie** [comment]
Cool - I see you've implemented all the relevant changes in the branch so I'll close this now. 👍

**Pull request closed without merging**
