### PR TITLE
Writer and Result classes for printing a QR-Code on a console

### PR DESCRIPTION
**Pull request by Trismegiste**
Hello,

I've created a new Writer for printing a QR Code on Command Line Interface. I find it very useful to get data or link from a server to your smartphone.

You can expect something like this for example :

Capture d’écran de 2022-06-30 10-53-16

(since it uses UTF-8, it should probably fail on Windows)

## Usage
```php
require_once __DIR__ . '/vendor/autoload.php';

use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\Writer\ConsoleWriter;

$result = Builder::create()
        ->writer(new ConsoleWriter())
        ->data($argv[1])
        ->build();

echo $result->getString();
```

Hope this helps :cherry_blossom:

### CODE REVIEW

**Comment by Trismegiste** [comment]
Sorry, took me a while to check with PHPStan

**Comment by endroid** [comment]
@Trismegiste sorry for the late response. I was enjoying my vacation ;) Really nice feature, great addition! Regarding the dark mode: I would really prefer to use the current QR code foreground and background color for this. If you could make it so that those colors are used we can create a dark mode using the current interface (and if really wanted, create a separate MR for creating a global dark mode setting).

**Comment by Trismegiste** [comment]
Done :coffee:

**Comment by endroid** [comment]
@Trismegiste thank you. I have to fix some new QA issues I see (not caused by your changes) before I tag the new version.

**Comment by endroid** [comment]
Tag 4.5.0

**Pull request merged**
