### PR TITLE
Add support for label in the PDF writer.

### PR DESCRIPTION
**Pull request by thijskh**
Respects the common Label options, except specifying a custom font.

That would in theory also be possible with a little hoop jumping, but not in scope for me now.

### CODE REVIEW

**Comment by endroid** [comment]
Hi @thijskh thank you. Could you please add this to the 3.x branch instead of master? The master branch will be used for the upcoming 4.x release.

**Comment by endroid** [comment]
Not perfect yet but certainly a good start and feature to have. I will wait for PHP 8 support before tagging so you can use the 3.x-dev tag for now. Thanks again!

**Comment by stephanvierkant** [comment]
@endroid When can we expect a new release? Is there something that should be done before a new release?

**Comment by endroid** [comment]
Hi @stephanvierkant unfortunately PHP 8 compatibility on the 3.x branch is blocked for the moment so we have to wait. If you really need it to work in PHP 8 you can use the workaround described [in this issue](https://github.com/endroid/qr-code/issues/292). The 4.x release almost ready meanwhile but I can not give an estimate on the time as this depends very much on my time and energy in the evening hours :)

**Pull request merged**
